config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :schedules
  resources :members
  resources :messages

  match '/signup', to:'members#new',    via: 'get'
  match '/signin', to:'sessions#new',    via: 'get', as: 'signin'
  match '/signout', to:'sessions#destroy',    via: 'delete', as: 'signout'

  get 'registrations/index'
  get 'registrations/regist'

  get 'topviews/index'
  get 'registrations/sellect2'

  get 'registrations/hello'

  root to: "topviews#index"

  match ':controller(/:action(/:id))', via:[:get, :post, :patch]

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :member
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_member!, except: [:index]
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.order(:created_at).reverse_order
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.member_id = current_member.id
    
    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|      
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:member_id, :message)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--   <div class="field">
    <%= f.label :member_id %><br>
    <%= f.number_field :member_id %>
  </div>
  -->
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table border = 1>
  <thead>
    <tr>
      <th>Message_id</th>
      <th>Name</th>
      <th>Message</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
        <td><%= Member.find(message.member_id).name %></td>
        <td><%= message.message %></td>
        <td><%= link_to 'Show', message %></td>
        <% if current_member &&  current_member.id == message.member_id %>
          <!-- ><td><%= link_to 'Edit', edit_message_path(message) %></td> -->
          <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %> </br>
<%= link_to 'Back TopView', topviews_index_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @message.member_id %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<!-- <%= link_to 'Edit', edit_message_path(@message) %> | -->
<%= link_to 'Back', messages_path %>